steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/main-cocoa-411512/hello-world', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/main-cocoa-411512/hello-world']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'hello-world'
  - '--image'
  - 'gcr.io/main-cocoa-411512/hello-world'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1'
env:
- 'CLOUDSDK_COMPUTE_ZONE=us-central1'
- 'CLOUDSDK_CORE_PROJECT=main-cocoa-411512'
options:
  logging:
    'cloudBuildersLogLevel': 'DEBUG'
